### ISSUE TITLE
Prikaz liste problema

### ISSUE THREAD

**Issue by stefan096** [stefan096/UKS#7]
Kao ulogovani korisnik, želim da mogu da pregledam sve probleme na projektu. Problemi trebaju biti grupisani u trenutno otvorene i zatvorene.

Na listi problema vidi se ko je kreirao problem, kada, naziv problema i njegov id. Naziv služi kao link do detalja problema.

**Comment by kristina-grujic** [comment]
Trenutno se prikazuje samo naziv problema i link do detalja, treba dodati ostale informacije - zbog toga cu prebaciti ovo u sledeci milestone
