### ISSUE TITLE
Prikaz pojedinog problema (detaljnije)

### ISSUE THREAD

**Issue by stefan096** [stefan096/UKS#8]
Kao ulogovani korisnik, želim da mogu da pregledam detalje prijavljenog problema.

Detalji podrazumevaju naziv, kada je kreiran problem, ko ga je kreirao, listu komentara vezanih za problem, dodeljene labele i kontrolnu tačku, kao i ko je zadužen za rešavanje problema.

**Comment by kristina-grujic** [comment]
Treba prikazati sve informacije, trenutno postoji samo naziv i dummy stranica, zato prebacujem u sledeci sprint
